name: OpenWrtNanoPi R2S

on:
  push:
    branches:
      - master
    paths:
      - 'build-number'
    tags-ignore:
      - build*

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Setup timezone
        uses: zcong1993/setup-timezone@v1.0
        with:
          timezone: Asia/Shanghai

      - name: Checkout
        uses: actions/checkout@v2.3.2
        with:
          ref: master

      - name: Init Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* android*
          sudo apt-get update
          sudo apt-get -y upgrade
          sudo -E apt-get -y install subversion build-essential libncurses5-dev zlib1g-dev gawk git ccache gettext libssl-dev xsltproc zip
          sudo apt-get -y autoremove --purge
          sudo apt-get clean

          git config --local user.email "i@shensven.com"
          git config --local user.name "GenSven"
          df -h

      - name: Get Source Code
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt/
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Generate Configuration File
        run: |
          cp config_r2s_shensven openwrt/.config

      - name: Build OpenWrt
        run: |
          cd openwrt/
          make defconfig
          make download -j8
          make -j1 V=s
          df -h

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: OpenWrt_for_NanoPi_R2S
          path: openwrt/bin/
